### ISSUE TITLE
Build for OS X

### ISSUE THREAD

**Issue by AlexFridman** [aklexel/vlc-tip-plugin#2]
Please, provide instructions how to build on Mac.

**Comment by aklexel** [comment]
I'm not quite sure but you can try to use the same Makefile to build the plugin on Mac. Take a note on the file extension, for Mac you need to rename libtip_plugin.so to libtip_plugin.dylib

To build the plugin on Linux (Ubuntu) you need to run the following commands:
`sudo apt-get install vlc libvlc-dev libvlccore-dev gcc make pkg-config`
`make`

I suppose that you need to run some similar commands to build the plugin on Mac.

**Comment by AlexFridman** [comment]
I will try soon. Thank you!

**Comment by aklexel** [comment]
Added [BUILD.md](https://github.com/aklexel/vlc-tip-plugin/blob/master/BUILD.md) with instructions to build the plugin on macOS.
