### ISSUE TITLE
Add subtitles activation feature

### ISSUE THREAD

**Issue by BiTOk** [aklexel/vlc-tip-plugin#3]
It would be great if it were possible to activate the subtitles with the translation or instead of it.

**Comment by ilyapt** [comment]
Strongly agree, subtitles help to recognize words.

**Comment by aklexel** [comment]
Implemented the subtitles switching feature. Now you can choose an audio track number and subtitle track number for translation and an subtitle track number for repeat. Also you can set -1 to disable switching audio/subtitle track during translation/repeat.
