### ISSUE TITLE
Add plugin build for MacOS

### ISSUE THREAD

**Issue by rimvaliulin** [aklexel/vlc-tip-plugin#4]
It will be nice to add plugin build for MacOS.

**Comment by aklexel** [comment]
I added the plugin build for macOS 64-bit ([libtip_plugin.dylib](https://github.com/aklexel/vlc-tip-plugin/raw/master/build/macos/64/libtip_plugin.dylib)). Please let me know if it works or not.

**Comment by rimvaliulin** [comment]
It works perfect.
