### ISSUE TITLE
Doesn't work at all (Windows 64-bit)

### ISSUE THREAD

**Issue by bullybutcher** [aklexel/vlc-tip-plugin#6]
VLC recognizes the plugin but the keyboard shortcuts do nothing

**Comment by aklexel** [comment]
What version of VLC do you use? Do you restart VLC after enabling the TIP plugin in preferences? 

Also, please note that the plugin shortcuts work in English keyboard layout only. So try to change keyboard layout to English.

**Comment by bullybutcher** [comment]
How do you enable the TIP plugin in preferences? There is no option apart from Translation settings and Repeat settings.

**Comment by aklexel** [comment]
To activate the TIP plugin, go to Preferences > All > Interface > Control interfaces and check "TIP (translate it, please)". Then restart VLC.

**Comment by bullybutcher** [comment]
![image](https://user-images.githubusercontent.com/34742984/119234833-7fc8fe80-bb62-11eb-9d79-a41d1f2f80ec.png)
There is no check. This is all I see.

**Comment by aklexel** [comment]
![vlc-tip-plugin-check](https://user-images.githubusercontent.com/14823342/119236693-8004d200-bb41-11eb-9aba-05f65e6dbbb9.png)
